project done
ElShaer398/codding-challenge-EGR-LB pull request #1
Opened 2022-12-08 16:37 UTC by ElShaer398

2022-12-08 16:47 UTC, ElShaer398 commented
Hi
Good work so far but the project needs some improvements.

1. You should use linters to check for any errors or styling problems.
2. Please stick to the colors provided in the template.

Kindly check any other required changes in comments.

2022-12-08 16:52 UTC, ElShaer398 commented on index.html
> +          <h1>Handcrafted, home-made masterpieces</h1>
Kindly adjust your tabs for clean code.

2022-12-08 16:53 UTC, ElShaer398 commented on index.html
> +    <h3 class="materials_h3">
Kindly put h3 in one line.

2022-12-08 16:54 UTC, ElShaer398 commented on style.css
> +html, body {
You can remove fixed height and width for responsive design.

2022-12-08 16:56 UTC, ElShaer398 commented on style.css
> +  height: 50px;;
There is an extra semicolon please remove it.

2022-12-08 16:57 UTC, ElShaer398 commented on style.css
> +.trombone{
Please use tabs in the right way for clean code.

2022-12-08 16:58 UTC, ElShaer398 commented on style.css
> +  background-color: #333333;
Please use the right color for the text to appear clearly.

2022-12-08 17:11 UTC, binhussen commented on style.css
> +  height: 50px;;
- Kindly, be polite when you give suggestions and raise the reasons 👌👍

2022-12-08 17:12 UTC, binhussen commented on style.css
> +.trombone{
- Kindly be reasonable when you give suggestions.👌👍

2022-12-08 17:14 UTC, binhussen commented on style.css
> +  background-color: #333333;
- Kindly, mention the reason and why they have to change.👌👍

2022-12-08 17:16 UTC, binhussen commented on index.html
> +    <h3 class="materials_h3">
- Kindly mention the reason why you are giving the suggestion 👌👍

2022-12-08 17:21 UTC, binhussen requested changes
Hi @ElShaer398 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
- Kindly, be polite and reasonable when you give sessions 👌👍

## Optional suggestions
- I think it will be great if you use a couple of emojis and/or gifs in the review. They make the code review more human-friendly 👽🤖.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 19:03 UTC, Lizdev-05 approved these changes
Hi @ElShaer398, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/hm8YCJd7ORdC70I6S3/giphy.gif"/>
## Highlights
- Polite words are used ✅
- Reasons for the changes are made known ✅
## Optional suggestions
- I think it will be good if you make use of emojis and gifs, it will make the reviewer to appear friendly.😎😊
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 19:16 UTC, merged